"""Device decoder registry.

Add a new decoder by importing it here and appending an instance to
DEVICE_REGISTRY.  Each decoder must implement:

    def decode(self, pulses: list[Pulse], freq_hz: float) -> DecodedPacket | None
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..dsp import Pulse
    from ..packet import DecodedPacket

# ---- bbq / pool / rain -------------------------------------------------
from .bbq_pool_rain import (
    BaldrHCS528ARF,
    BaldrRain,
    BiltemaRain,
    EmosE6016Rain,
    GrillThermometer,
    MaverickET73,
    MaverickET73x,
    MaverickXR30,
    MaverickXR50,
    QuiggBBQ,
    RainPointHCS012ARF,
    RainPointSoil,
    RubicsonPool48942,
    Schou72543Rain,
    SRSmithPool,
    TFAPoolThermometer,
    TSFT002,
    TyphurSyncGold,
)

# ---- car remotes -------------------------------------------------------
from .car_remotes import (
    AstrostartCarRemote,
    AudiovoxProOE3B,
    ChryslerCarRemote,
    CodeAlarmCarRemote,
    ContinentalCarRemote,
    Compustar1WG3R,
    FordRemote,
    GMCarRemote,
    HondaRemote,
    Mic6SC2CarRemote,
    NidecCarRemote,
    OpelMokka,
)

# ---- misc --------------------------------------------------------------
from .misc import (
    AbmtDecoder,
    Akhan100F14,
    AlpsFwb1u545,
    AntAntplus,
    ArchosTbh,
    AradMsMeter,
    Bm5,
    Ced7000,
    CelsiaCzc1,
    ChamberlainCwpirc,
    Cmr113,
    CompanionWtr001,
    CttLifePowerHybrid,
    DirecTV,
    DishRemote63,
    Ecodhome,
    En2058,
    EsunEn2053,
    FslScoreboard,
    GenericRemote,
    HanwellML4000,
    Ht680,
    IbisBeacon,
    Insteon,
    MartecMplcd,
    Megacode,
    MissilMl0757,
    MuellerHotrod,
    OmniMultisensor,
    OpusXT300,
    PhilipsAJ3650,
    PhilipsAJ7010,
    Proflame2,
    Quinetic,
    RadioheadASK,
    RFTech,
    Rfm69Moteino,
    RosstechDcu706,
    Siemens5wy72xx,
    Tr502msv,
    TwogigKey2e,
    WgPb12v1,
)

# ---- missing / late additions ------------------------------------------
from .missing import (
    BtRain,
    ElroDb286a,
    ElsnerSolexa,
    ElvEM1000,
    ElvWS2000,
    ESA1000,
    GtTmbbq05,
    HomeleadHG9901,
    TelldusFT0385R,
    ThermorDG950,
    ThermorA6N132TX,
    WallarGeCLTX001,
)

# ---- power / energy ----------------------------------------------------
from .power_energy import (
    BluelinePowerCost,
    BurnhardBBQ,
    CurrentCost,
    EC3k,
    EcoEye,
    EfergyE2Classic,
    EfergyOptical,
    ElsterPowerMeter,
    EmonTX,
    ESICEmt7110,
    GasmateBA1008,
    GeoMinim,
    IkeaSparsnas,
    MarlecSolar,
    RFXMeter,
    RevoltNC5462,
    RevoltZX7717,
)

# ---- security ----------------------------------------------------------
from .security import (
    CaviusSensor,
    ChuangoSecurity,
    DSCSecurity,
    GenericMotion,
    HCS200,
    HCS361,
    HCS362,
    HoneywellCM921,
    HoneywellSecurity,
    HoneywellWDB,
    InterlogixSecurity,
    KeruiSensor,
    KiddeSmokeAlarm,
    RiscoAgility,
    RoboguardIQBlue,
    SecplusV1,
    SecplusV2,
    SimpliSafe,
    SimpliSafeGen3,
    SmokeGS558,
    VisonicPowercode,
    VivintSensor,
    YaleHSA,
)

# ---- smart home --------------------------------------------------------
from .smart_home import (
    BlyssDC5,
    BrennenstuhlRCS2044,
    Cardin,
    Danfoss,
    DeltaDoreX3D,
    DickertMAHS,
    EberleInstat868R1,
    Elero,
    EnOceanERP1,
    FS20,
    FlorabBest,
    Funkbus,
    GEColorEffects,
    InoValleyKW9015B,
    Intertechno,
    Jasco,
    LightwaveRF,
    MCPowerKinetic,
    Markisol,
    NewKAKU,
    Nexa,
    NiceFloRS,
    Norgo,
    Quhwa,
    RegencyFan,
    RojaFlex,
    Silvercrest,
    SomfyIOHC,
    SomfyRTS,
    UniversalFanCtrl,
    VaillantVRT340F,
    WattsThermostat,
    WattsVision,
    WattsWFHTRF,
    Waveman,
    X10RF,
    X10Sec,
)

# ---- TPMS (all three source groups merged into one package) ------------
from .tpms import (
    # Euro
    Schraeder,
    SchraeaderEG53MA4,
    SchraeaderMRXBC5A4,
    SchraeaderNIS315G3,
    SchraeaderSMD3MA4,
    TPMSAbarth124,
    TPMSBmw,
    TPMSBmwG3,
    TPMSCitroen,
    TPMSHyundaiVDO,
    TPMSMercedesBenz,
    TPMSPorsche,
    TPMSRenault,
    TPMSRenault0435R,
    TPMSSefisM3,
    TPMSTRW,
    # USA
    Steelmate,
    TpmsElantra2012,
    TpmsFord,
    TpmsGm,
    TpmsHonda,
    TpmsKia,
    TpmsNissan,
    TpmsSmartire,
    TpmsToyota,
    TpmsTruck,
    TpmsTyreguard400,
    # Misc
    TpmsAirpuxem,
    TpmsAve,
    TpmsEezrv,
    TpmsGearHive,
    TpmsImarsT240,
    TpmsJansite,
    TpmsJansiteSolar,
    TpmsJansiteTy468,
    TpmsJansiteTy588,
    TpmsJeep,
    TpmsPmv107j,
    TpmsSchraderMotorcycle,
)

# ---- water meters ------------------------------------------------------
from .water_meters import (
    ApatorMetraEitn30,
    ApatorMetraErm30,
    AradMsMeter as AradMsMeterWater,
    BadgerOrionEndpoint,
    BadgerWater,
    ErtIdm,
    ErtScm,
    Flowis,
    Gridstream,
    MBus,
    NeptuneR900,
    NeptuneR900BCD,
    OilSmart,
    OilStandard,
    OilWatchman,
    OilWatchmanAdvanced,
    ScmPlus,
    SilverSpringMesh,
    WatchmanPlus,
)

# ---- weather (all groups: nexus/lacrosse/acurite/bresser/fineoffset/
#      govee/hideki/oregon/tfa/thermopro/auriol + 3 legacy classes) -----
from .weather import (
    # legacy (from old acurite.py, fineoffset.py, nexus.py)
    Acurite609,
    FineOffsetWH2,
    NexusTHLegacy as NexusTH,          # legacy simplified decoder; registered first
    # nexus / cotech group
    NexusTH as NexusTHWeatherNexus,    # full nexus/cotech family decoder
    Rubicson,
    Rubicson48659,
    Prologue,
    Proove,
    Kedsum,
    S3318P,
    TTX201,
    CalibeursRF104,
    GtWt02,
    GtWt03,
    Mebus,
    Eurochron,
    Cotech36_7900,
    Cotech36_7959,
    CotechFT0203,
    DigitechXC0324,
    SolightTE44,
    # lacrosse group
    LaCrosseTX,
    LaCrosseTX141x,
    LaCrosseWS7000,
    LaCrosseWS2310,
    LaCrosseTH3,
    LaCrosseR1,
    LaCrosseTX22UIT,
    LaCrosseTX31U,
    LaCrosseTX34,
    LaCrosseTX35,
    LaCrosseWR1,
    LaCrosseWS6868,
    LaCrosseBreezePro,
    # acurite group
    AcuriteRain896,
    AcuriteTH,
    AcuriteTXR,
    Acurite986,
    Acurite985,
    Acurite606,
    Acurite00275RM,
    Acurite590TX,
    Acurite01185M,
    # bresser group
    Bresser3CH,
    Bresser5in1,
    Bresser6in1,
    Bresser7in1,
    BresserGarden,
    BresserLeakage,
    BresserLightning,
    BresserST1005H,
    # fineoffset group
    FineOffsetWH1050,
    FineOffsetWH1080,
    FineOffsetWH31L,
    FineOffsetWH43,
    FineOffsetWH45,
    FineOffsetWH46,
    FineOffsetWH52,
    FineOffsetWH55,
    FineOffsetWN34,
    FineOffsetWS80,
    FineOffsetWS85,
    FineOffsetWS90,
    # govee group
    AmbientWeatherF007TH,
    AmbientWeatherTX8300,
    AmbientWeatherWH31E,
    Ecowitt,
    GoveeH5054,
    GoveeH5054v2,
    GoveeH5059,
    GoveeH5112,
    GoveeH5310,
    # hideki group
    ArexxML,
    AtechWS308,
    BaldrTherm,
    EmosE6016,
    FT004B,
    HidekiTS04,
    KlimaLogg,
    Vevor7in1,
    WEC2103,
    # oregon group
    OregonScientific,
    OregonScientificSL109H,
    OregonScientificV1,
    OregonScientificWMR500,
    # tfa group
    TFA14_1504_V2,
    TFA30_3196,
    TFA30_3221,
    TFA30_3307,
    TFA30_390X,
    TFADrop303233,
    TFAMarbella,
    TFAPoolThermometer as TFAPoolThermometerTFA,
    TFATwinPlus303049,
    # thermopro group
    ThermoProTP11,
    ThermoProTP12,
    ThermoProTP211B,
    ThermoProTP28b,
    ThermoProTP828b,
    ThermoProTP829b,
    ThermoProTP86xb,
    ThermoProTX2,
    ThermoProTX2C,
    ThermoProTX7B,
    # auriol_a group
    AlectoV1,
    Auriol4LD5661,
    Auriol4LD6654,
    AuriolAFT77B2,
    AuriolAFW2A1,
    AuriolAHFL,
    AuriolHG02832,
    AuriolHG04641A,
    GeevonTX16,
    GeevonTX19,
    HolmanWS5029PCM,
    HolmanWS5029PWM,
    InFactory,
    InkbirdITH20R,
    WT450,
    # auriol_b group
    EFTH800,
    EmaxW6,
    EsperanzaEWS,
    GenericTemperatureSensor,
    NetatmoTHW,
    OriaWA150KM,
    SainlogicSA8,
    SharpSPC775,
    ShenzhenWaleWLTH6R,
    SpringfieldSoilMoisture,
    VaunoEN8822C,
    WT0124PoolThermometer,
    WS2032,
    WSSensor,
)


# OOK device decoders  tried in order; first match wins.
DEVICE_REGISTRY: list = [
    # Legacy decoders (kept early for backward compat)
    NexusTH(),
    FineOffsetWH2(),
    Acurite609(),
    # bbq_pool_rain
    BaldrHCS528ARF(),
    BaldrRain(),
    BiltemaRain(),
    EmosE6016Rain(),
    GrillThermometer(),
    MaverickET73(),
    MaverickET73x(),
    MaverickXR30(),
    MaverickXR50(),
    QuiggBBQ(),
    RainPointHCS012ARF(),
    RainPointSoil(),
    RubicsonPool48942(),
    Schou72543Rain(),
    SRSmithPool(),
    TFAPoolThermometer(),
    TSFT002(),
    TyphurSyncGold(),
    # car_remotes
    AstrostartCarRemote(),
    AudiovoxProOE3B(),
    ChryslerCarRemote(),
    CodeAlarmCarRemote(),
    ContinentalCarRemote(),
    Compustar1WG3R(),
    FordRemote(),
    GMCarRemote(),
    HondaRemote(),
    Mic6SC2CarRemote(),
    NidecCarRemote(),
    OpelMokka(),
    # misc
    AbmtDecoder(),
    Akhan100F14(),
    AlpsFwb1u545(),
    AntAntplus(),
    ArchosTbh(),
    AradMsMeter(),
    Bm5(),
    Ced7000(),
    CelsiaCzc1(),
    ChamberlainCwpirc(),
    Cmr113(),
    CompanionWtr001(),
    CttLifePowerHybrid(),
    DirecTV(),
    DishRemote63(),
    Ecodhome(),
    En2058(),
    EsunEn2053(),
    FslScoreboard(),
    GenericRemote(),
    HanwellML4000(),
    Ht680(),
    IbisBeacon(),
    Insteon(),
    MartecMplcd(),
    Megacode(),
    MissilMl0757(),
    MuellerHotrod(),
    OmniMultisensor(),
    OpusXT300(),
    PhilipsAJ3650(),
    PhilipsAJ7010(),
    Proflame2(),
    Quinetic(),
    RadioheadASK(),
    RFTech(),
    Rfm69Moteino(),
    RosstechDcu706(),
    Siemens5wy72xx(),
    Tr502msv(),
    TwogigKey2e(),
    WgPb12v1(),
    # power_energy
    BluelinePowerCost(),
    BurnhardBBQ(),
    CurrentCost(),
    EC3k(),
    EcoEye(),
    EfergyE2Classic(),
    EfergyOptical(),
    ElsterPowerMeter(),
    EmonTX(),
    ESICEmt7110(),
    GasmateBA1008(),
    GeoMinim(),
    IkeaSparsnas(),
    MarlecSolar(),
    RFXMeter(),
    RevoltNC5462(),
    RevoltZX7717(),
    # security
    CaviusSensor(),
    ChuangoSecurity(),
    DSCSecurity(),
    GenericMotion(),
    HCS200(),
    HCS361(),
    HCS362(),
    HoneywellCM921(),
    HoneywellSecurity(),
    HoneywellWDB(),
    InterlogixSecurity(),
    KeruiSensor(),
    KiddeSmokeAlarm(),
    RiscoAgility(),
    RoboguardIQBlue(),
    SecplusV1(),
    SecplusV2(),
    SimpliSafe(),
    SimpliSafeGen3(),
    SmokeGS558(),
    VisonicPowercode(),
    VivintSensor(),
    YaleHSA(),
    # smart_home
    BlyssDC5(),
    BrennenstuhlRCS2044(),
    Cardin(),
    Danfoss(),
    DeltaDoreX3D(),
    DickertMAHS(),
    EberleInstat868R1(),
    Elero(),
    EnOceanERP1(),
    FS20(),
    FlorabBest(),
    Funkbus(),
    GEColorEffects(),
    InoValleyKW9015B(),
    Intertechno(),
    Jasco(),
    LightwaveRF(),
    MCPowerKinetic(),
    Markisol(),
    NewKAKU(),
    Nexa(),
    NiceFloRS(),
    Norgo(),
    Quhwa(),
    RegencyFan(),
    RojaFlex(),
    Silvercrest(),
    SomfyIOHC(),
    SomfyRTS(),
    UniversalFanCtrl(),
    VaillantVRT340F(),
    WattsThermostat(),
    WattsVision(),
    WattsWFHTRF(),
    Waveman(),
    X10RF(),
    X10Sec(),
    # tpms  euro
    Schraeder(),
    SchraeaderEG53MA4(),
    SchraeaderMRXBC5A4(),
    SchraeaderNIS315G3(),
    SchraeaderSMD3MA4(),
    TPMSAbarth124(),
    TPMSBmw(),
    TPMSBmwG3(),
    TPMSCitroen(),
    TPMSHyundaiVDO(),
    TPMSMercedesBenz(),
    TPMSPorsche(),
    TPMSRenault(),
    TPMSRenault0435R(),
    TPMSSefisM3(),
    TPMSTRW(),
    # tpms  misc
    TpmsAirpuxem(),
    TpmsAve(),
    TpmsEezrv(),
    TpmsGearHive(),
    TpmsImarsT240(),
    TpmsJansite(),
    TpmsJansiteSolar(),
    TpmsJansiteTy468(),
    TpmsJansiteTy588(),
    TpmsJeep(),
    TpmsPmv107j(),
    TpmsSchraderMotorcycle(),
    # tpms  usa
    Steelmate(),
    TpmsElantra2012(),
    TpmsFord(),
    TpmsGm(),
    TpmsHonda(),
    TpmsKia(),
    TpmsNissan(),
    TpmsSmartire(),
    TpmsToyota(),
    TpmsTruck(),
    TpmsTyreguard400(),
    # water_meters
    ApatorMetraEitn30(),
    ApatorMetraErm30(),
    AradMsMeterWater(),
    BadgerOrionEndpoint(),
    BadgerWater(),
    ErtIdm(),
    ErtScm(),
    Flowis(),
    Gridstream(),
    MBus(),
    NeptuneR900(),
    NeptuneR900BCD(),
    OilSmart(),
    OilStandard(),
    OilWatchman(),
    OilWatchmanAdvanced(),
    ScmPlus(),
    SilverSpringMesh(),
    WatchmanPlus(),
    # weather  acurite
    Acurite00275RM(),
    Acurite01185M(),
    Acurite590TX(),
    Acurite606(),
    Acurite985(),
    Acurite986(),
    AcuriteRain896(),
    AcuriteTH(),
    AcuriteTXR(),
    # weather  bresser
    Bresser3CH(),
    Bresser5in1(),
    Bresser6in1(),
    Bresser7in1(),
    BresserGarden(),
    BresserLeakage(),
    BresserLightning(),
    BresserST1005H(),
    # weather  fineoffset
    FineOffsetWH1050(),
    FineOffsetWH1080(),
    FineOffsetWH31L(),
    FineOffsetWH43(),
    FineOffsetWH45(),
    FineOffsetWH46(),
    FineOffsetWH52(),
    FineOffsetWH55(),
    FineOffsetWN34(),
    FineOffsetWS80(),
    FineOffsetWS85(),
    FineOffsetWS90(),
    # weather  govee
    AmbientWeatherF007TH(),
    AmbientWeatherTX8300(),
    AmbientWeatherWH31E(),
    Ecowitt(),
    GoveeH5054(),
    GoveeH5054v2(),
    GoveeH5059(),
    GoveeH5112(),
    GoveeH5310(),
    # weather  hideki
    ArexxML(),
    AtechWS308(),
    BaldrTherm(),
    EmosE6016(),
    FT004B(),
    HidekiTS04(),
    KlimaLogg(),
    Vevor7in1(),
    WEC2103(),
    # weather  nexus / cotech
    CalibeursRF104(),
    Cotech36_7900(),
    Cotech36_7959(),
    CotechFT0203(),
    DigitechXC0324(),
    Eurochron(),
    GtWt02(),
    GtWt03(),
    Kedsum(),
    Mebus(),
    NexusTHWeatherNexus(),
    Prologue(),
    Proove(),
    Rubicson(),
    Rubicson48659(),
    S3318P(),
    SolightTE44(),
    TTX201(),
    # weather  lacrosse
    LaCrosseTX(),
    LaCrosseTX141x(),
    LaCrosseWS7000(),
    LaCrosseWS2310(),
    LaCrosseTH3(),
    LaCrosseR1(),
    LaCrosseTX22UIT(),
    LaCrosseTX31U(),
    LaCrosseTX34(),
    LaCrosseTX35(),
    LaCrosseWR1(),
    LaCrosseWS6868(),
    LaCrosseBreezePro(),
    # weather  oregon
    OregonScientific(),
    OregonScientificSL109H(),
    OregonScientificV1(),
    OregonScientificWMR500(),
    # weather  tfa
    TFA14_1504_V2(),
    TFA30_3196(),
    TFA30_3221(),
    TFA30_3307(),
    TFA30_390X(),
    TFADrop303233(),
    TFAMarbella(),
    TFAPoolThermometerTFA(),
    TFATwinPlus303049(),
    # weather  thermopro
    ThermoProTP11(),
    ThermoProTP12(),
    ThermoProTP211B(),
    ThermoProTP28b(),
    ThermoProTP828b(),
    ThermoProTP829b(),
    ThermoProTP86xb(),
    ThermoProTX2(),
    ThermoProTX2C(),
    ThermoProTX7B(),
    # weather  auriol_a
    AlectoV1(),
    Auriol4LD5661(),
    Auriol4LD6654(),
    AuriolAFT77B2(),
    AuriolAFW2A1(),
    AuriolAHFL(),
    AuriolHG02832(),
    AuriolHG04641A(),
    GeevonTX16(),
    GeevonTX19(),
    HolmanWS5029PCM(),
    HolmanWS5029PWM(),
    InFactory(),
    InkbirdITH20R(),
    WT450(),
    # weather  auriol_b
    EFTH800(),
    EmaxW6(),
    EsperanzaEWS(),
    GenericTemperatureSensor(),
    NetatmoTHW(),
    OriaWA150KM(),
    SainlogicSA8(),
    SharpSPC775(),
    ShenzhenWaleWLTH6R(),
    SpringfieldSoilMoisture(),
    VaunoEN8822C(),
    WT0124PoolThermometer(),
    WS2032(),
    WSSensor(),
    # missing / late additions
    BtRain(),
    ElroDb286a(),
    ElsnerSolexa(),
    ElvEM1000(),
    ElvWS2000(),
    ESA1000(),
    GtTmbbq05(),
    HomeleadHG9901(),
    TelldusFT0385R(),
    ThermorDG950(),
    ThermorA6N132TX(),
    WallarGeCLTX001(),
]


def try_decode(pulses: "list[Pulse]", freq_hz: float) -> "DecodedPacket | None":
    for decoder in DEVICE_REGISTRY:
        result = decoder.decode(pulses, freq_hz)
        if result is not None:
            return result
    return None
